stages:
  - test
  - deploy

custom-tests:
  stage: test
  image: none
  script:
    - python3 -m pip install --upgrade pip
    - pip3 install -r requirements.txt
    - python3 ppsv/manage.py check
    - python3 ppsv/manage.py makemigrations --check
    - chmod +x tests/test.sh
    - ./tests/test.sh -save

deploy-prod:
  stage: deploy
  image: none
  only:
    refs:
        - master
  script:
    - echo "Building docker images and start containers ..."
    - chmod +x start-production.sh
    - ./start-production.sh
