stages:
  - test
  - deploy

custom-tests:
  stage: test
  image: none
  script:
    - alias python="python3"
    - alias pip="pip3"
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - python ppsv/manage.py check
    - python ppsv/manage.py makemigrations --check
    - chmod +x tests/test.sh
    - ./tests/test.sh -save

deploy-prod:
  stage: deploy
  image: none
  only:
    refs:
        - master
  script:
    - echo "Building docker images and start containers ..."
    - chmod +x start-production.sh
    - ./start-production.sh
