stages:
  - test

custom-tests:
  stage: test
  tags:
    - pi
  script:
    - python3 -m pip install --upgrade pip
    - pip3 install -r requirements.txt
    - cd ppsv/
    - python3 manage.py check
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python manage.py test --parallel 4 --timing -v 3

