# Generated by Django 4.0 on 2023-04-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_assignment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.PositiveIntegerField(verbose_name='SlotID')),
                ('finalized_slot', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TermFinalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mails_send', models.BooleanField(default=False)),
                ('finalized', models.BooleanField(default=False)),
            ],
        ),
    ]
