# Generated by Django 4.0 on 2023-01-10 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0020_alter_course_motivation_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.PositiveIntegerField(verbose_name='SlotID')),
                ('accepted_applications', models.ManyToManyField(to='course.TopicSelection', verbose_name='Accepted Applications')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.topic', verbose_name='Topic')),
            ],
        ),
    ]
