# Generated by Django 4.0 on 2023-04-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termfinalization',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.term'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='accepted_applications',
            field=models.ManyToManyField(through='backend.AcceptedApplications', to='base.TopicSelection', verbose_name='Accepted Applications'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.topic', verbose_name='Topic'),
        ),
        migrations.AddField(
            model_name='acceptedapplications',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.assignment'),
        ),
        migrations.AddField(
            model_name='acceptedapplications',
            name='topic_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.topicselection'),
        ),
    ]
