# Generated by Django 4.0 on 2023-01-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_remove_course_collection_exclusive_and_more'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_assignment', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='finalized_slot',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='accepted_applications',
            field=models.ManyToManyField(to='course.TopicSelection', verbose_name='Accepted Applications'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='accepted_applications',
            field=models.ManyToManyField(through='backend.AcceptedApplications', to='course.TopicSelection',
                                         verbose_name='Accepted Applications'),
        ),
        migrations.AddField(
            model_name='acceptedapplications',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.assignment'),
        ),
        migrations.AddField(
            model_name='acceptedapplications',
            name='topic_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.topicselection'),
        ),
    ]
