# Generated by Django 4.0 on 2023-01-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_acceptedapplications_assignment_finalized_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedapplications',
            name='finalized_assignment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='finalized_slot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
