# Generated by Django 4.0 on 2023-01-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_acceptedapplications_finalized_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedapplications',
            name='finalized_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
