# Generated by Django 4.0 on 2023-03-19 14:01

from django.db import migrations


def create_teacher_group(apps, schema_editor):
    """
    Function for creating the teachers group
    """
    Group = apps.get_model('auth', 'group')
    Group.objects.get_or_create(name='teacher')


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_teacher_group)
    ]
