# Generated by Django 3.2.9 on 2021-11-29 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_type', models.CharField(max_length=200)),
                ('register_from', models.DateTimeField(verbose_name='date registration opens')),
                ('registration_deadline', models.DateTimeField(verbose_name='registration deadline')),
                ('course_description', models.TextField(verbose_name='course description')),
                ('max_participants', models.IntegerField(default=9999, verbose_name='maximum number of participants')),
                ('cp', models.IntegerField(verbose_name='CP')),
                ('category', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('tucan_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('max_participants', models.IntegerField(default=999, verbose_name='maximum number of participants')),
                ('topic_description', models.TextField(verbose_name='topic description')),
                ('topic_file', models.FileField(upload_to='course_directory_path')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
