# Generated by Django 3.2.9 on 2021-12-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_squashed_0009_auto_20211202_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
    ]
