# Generated by Django 3.2.9 on 2021-12-14 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_name_course_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='textsaves',
            options={'verbose_name': 'text Save', 'verbose_name_plural': 'text Saves'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
        migrations.AlterModelOptions(
            name='topicselection',
            options={'verbose_name': 'topic Selection', 'verbose_name_plural': 'topic Selections'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(choices=[('FB01', 'Dept. 01 - Law and Economics'), ('FB02', 'Dept. 02 - History and Social Sciences'), ('FB03', 'Dept. 03 - Human Sciences'), ('FB04', 'Dept. 04 - Mathematics'), ('FB05', 'Dept. 05 – Physics'), ('FB07', 'Dept. 07 - Chemistry'), ('FB10', 'Dept. 10 - Biology'), ('FB11', 'Dept. 11 - Materials and Earth Sciences'), ('FB13', 'Dept. 13 - Civil and Environmental Engineering'), ('FB15', 'Dept. 15 - Architecture'), ('FB16', 'Dept. 16 - Mechanical Engineering'), ('FB18', 'Dept. 18 - Electrical Engineering and Information Technology'), ('FB20', 'Dept. 20 - Computer Science')], max_length=4, verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_participants',
            field=models.IntegerField(default=9999, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='maximum Participants'),
        ),
        migrations.AlterField(
            model_name='course',
            name='organizer',
            field=models.CharField(max_length=200, verbose_name='organizer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_deadline',
            field=models.DateTimeField(verbose_name='registration Deadline'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration Start'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('SE', 'Seminar'), ('PR', 'Internship'), ('SO', 'Miscellaneous')], default='SE', max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='group',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='course.Topic', verbose_name='topics'),
        ),
        migrations.AlterField(
            model_name='group',
            name='size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='group Size'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='course.Student', verbose_name='students'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name='first Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tucan_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='student ID'),
        ),
        migrations.AlterField(
            model_name='textsaves',
            name='motivation',
            field=models.TextField(verbose_name='motivation Text'),
        ),
        migrations.AlterField(
            model_name='textsaves',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='textsaves',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, upload_to='course_directory_path', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='max_participants',
            field=models.IntegerField(default=9999, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='maximum Participants'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='topicselection',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='topicselection',
            name='motivation',
            field=models.TextField(verbose_name='motivation Text'),
        ),
        migrations.AlterField(
            model_name='topicselection',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.topic', verbose_name='topic'),
        ),
    ]
