# Generated by Django 3.2.9 on 2021-12-14 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20211214_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unlimited',
            field=models.BooleanField(blank=True, default=False, verbose_name='unlimited Participants'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_participants',
            field=models.IntegerField(default=9999, help_text='optional', validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)], verbose_name='maximum Participants'),
        ),
    ]
