# Generated by Django 3.2.9 on 2022-01-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20211220_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('SE', 'Seminar'), ('IN', 'Internship'), ('MI', 'Miscellaneous')], default='SE', max_length=2, verbose_name='type'),
        ),
    ]
