# Generated by Django 3.2.9 on 2022-01-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='motivation_text',
            field=models.BooleanField(blank=True, default=False, verbose_name='Do you want motivation texts for this course'),
        ),
    ]
