# Generated by Django 3.2.9 on 2022-01-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_motivation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='motivation_text',
            field=models.BooleanField(default=False, verbose_name='Do you want motivation texts for this course'),
        ),
    ]
