# Generated by Django 4.0 on 2022-01-24 20:33

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_course_motivation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='unlimited',
            field=models.BooleanField(blank=True, default=False, verbose_name='unlimited number of participants'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, upload_to=course.models.course_directory_path, verbose_name='file'),
        ),
    ]
