# Generated by Django 3.2.9 on 2022-01-30 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_course_motivation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='max_participants',
            field=models.IntegerField(default=9999, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)], verbose_name='maximum Participants'),
        ),
    ]
