# Generated by Django 4.0 on 2022-01-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_course_unlimited_alter_topic_file'),
        ('course', '0012_alter_topic_max_participants'),
    ]

    operations = [
    ]
