# Generated by Django 4.0 on 2022-03-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_course_collection_exclusive_group_collection_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicselection',
            name='collection_number',
            field=models.IntegerField(default=1, verbose_name='collection number'),
        ),
    ]
