# Generated by Django 4.0 on 2022-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_topicselection_collection_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursetype', models.CharField(max_length=200, verbose_name='coursetype')),
            ],
            options={
                'verbose_name': 'course Type',
                'verbose_name_plural': 'course Types',
            },
        ),
    ]
