# Generated by Django 4.0 on 2022-03-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_coursetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursetype', verbose_name='course'),
        ),
    ]
