# Generated by Django 4.0 on 2022-03-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_remove_coursetype_coursetype_coursetype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursetype', verbose_name='type'),
        ),
    ]
