# Generated by Django 4.0 on 2023-01-10 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('course', '0020_alter_course_motivation_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='collection_exclusive',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='course',
            name='unlimited',
        ),
        migrations.RemoveField(
            model_name='group',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='topic',
            name='max_slot_size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='max GroupSize'),
        ),
        migrations.AddField(
            model_name='topic',
            name='max_slots',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='max slot count'),
        ),
        migrations.AddField(
            model_name='topic',
            name='min_slot_size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='min GroupSize'),
        ),
    ]
